version: '{build}'

skip_tags: true
clone_depth: 10

environment:
  MAVEN_OPTS: -Xmx768m
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
      MVN_SYSTEM_PROPERTIES: -Dhttps.protocols=TLSv1.2
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: mvn --version
  - cmd: java -version

build_script:
  - mvn -B -Prun-its clean verify %MVN_SYSTEM_PROPERTIES%

cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2
